In [1]:
class Asmuo():
    pass

In [9]:
a1 = Asmuo()
a2 = Asmuo()

print(type(a1), type(a2), sep='\n')

Aš kątik atsiradau
Aš kątik atsiradau
<class '__main__.Asmuo'>
<class '__main__.Asmuo'>


In [8]:
#metodas:

Name = 'Petriukas'
class Asmuo():
    def __init__(self):
        print('Aš kątik atsiradau')
        self.Name = 'Jonukas' #klasės atributas. ,t.y. kintamasis klasės viduje
        pass

    def printName(self):
        print(Name)
        print(self.Name)

In [10]:
a1.printName()

Petriukas
Jonukas


In [11]:
#metodas:

class Asmuo():
    def __init__(self, name):
        self.Name = name #klasės atributas. ,t.y. kintamasis klasės viduje
        pass

    def printName(self):
        print(self.Name)

In [12]:
a1 = Asmuo('Jonukas')
a2 = Asmuo('Petriukas')

print(type(a1), type(a2), sep='\n')

<class '__main__.Asmuo'>
<class '__main__.Asmuo'>


In [13]:
a1.printName()
a2.printName()

Jonukas
Petriukas


In [46]:
#metodas:

class Asmuo():
    def __init__(self, name, gm):
        self.Name = name #klasės atributas. ,t.y. kintamasis klasės viduje
        self.BYear = gm
        # self.Age = 2024 - self.BYear
        self.Age = self.calculateAge()
        pass

    def getName(self):
        return self.Name
    
    def setName(self, new_name):
        self.Name = new_name
    def calculateAge(self):
        return 2024-self.BYear

In [43]:
a1 = Asmuo('Jonukas')
ats = a1.getName()
print(ats)
a1.Name = 'Marytė'
print(a1.getName())
a1.setName('Jonukas')
print(a1.getName())

TypeError: Asmuo.__init__() missing 1 required positional argument: 'gm'

In [47]:
a1 = Asmuo('Vardenis', 1996)
print(a1.Age, a1.getName())

28 Vardenis


In [48]:
# paveldėjimas

class Studentas(Asmuo):
    def getStatus(self):
        return 'Studentas'

In [49]:
std1 = Studentas('Unė', 1992)

In [50]:
print(std1.Age, std1.getName(), std1.getStatus())

32 Unė Studentas


In [51]:
class Studentas(Asmuo):
    def __init__(self, name, gm):
        super().__init__(name, gm)
        self.Enroll = True

std1 = Studentas('Unė', 1996)

In [52]:
print(std1.Age)

28

In [53]:
# aprašykite klasę Kvadratas
# kreipiantis į klasę, reikia nurodyti kvadrato ilgį a.
# Klasė turi turėti atributą Plotas, kurį 
# turi apskaičiuoti klasės kūrimo metu.
# Plotas = a*a
# parašykite metodą, kuris grąžintų apskaičiuoto Plotas atributo reikšmę.

class Kvadratas():
    def __init__(self, a):
        self.ilgis = a
        self.plotas = self.CalculatePlotas()
    
    def CalculatePlotas(self):
        return self.ilgis**2

In [55]:
kambario_plotas = Kvadratas(20)
print(kambario_plotas.plotas)

400


In [60]:
# aprašykite klasę Kvadratas
# kreipiantis į klasę, reikia nurodyti kvadrato ilgį a.
# Klasė turi turėti atributą Plotas, kurį 
# turi apskaičiuoti klasės kūrimo metu.
# Plotas = a*a
# parašykite metodą, kuris grąžintų apskaičiuoto Plotas atributo reikšmę.

class Kvadratas():
    def __init__(self, a):
        self.plotas = a*a
        self.perimetras = 4*a
    
    def CalculatePlotas(self):
        return self.plotas
    
    def CalculatePerimetras(self):
        return self.perimetras

In [69]:
sklypas = Kvadratas(20)
print(sklypas.plotas)
print(sklypas.perimetras)

400
80


In [65]:
# aprašykite klasę Rectangle
# kreipiantis į klasę, reikia nurodyti stačiakampio
# kraštines a ir b.
# Realizuokite atributą Plotas = a*b
# ir metodą, grąžinantį Ploto reikšmę
# Taip pat pridėkite metodą, apskaičiuojantį ir grąžinantį
# perimetrą P=2(a+b)

class Rectangle():
    def __init__(self, a, b):
        self.plotas = a*b
        self.perimetras = 2*(a+b)
    
    def CalculatePlotas(self):
        return self.plotas
    
    def CalculatePerimetras(self):
        return self.perimetras

In [70]:
sklypas = Rectangle(20, 10)
print(sklypas.plotas)
print(sklypas.perimetras)

200
60


In [67]:
# aprašykite klasę Cube (paviršiau plotas ir tūris)

class Cube():
    def __init__(self, a):
        self.plotas = a**2*6
        self.turis = a**3
    
    def CalculatePlotas(self):
        return self.plotas
    
    def CalculateVolume(self):
        return self.turis

In [71]:
kubas = Cube(10)
print(kubas.plotas)
print(kubas.turis)

600
1000


In [93]:
#susikurkite su Notepadu tekstinį failą su bet kokiu tekstu
#parašykite klasę TxtReader, kuriai kreipimosimetu būtų nurodomas tekstinio failo pavadinimas;
#klasės sukūrimo metu tas tekstinis failas turi būti nuskaitomas
#ir nuskaitytas tekstas turi būti priskirtas atributui Text
#parašykite metodą getText(), kuri grąžintų atributo text reikšmę

class TxtReader():
    def __init__(self, txt):
        self.Text = open(txt, mode='r', encoding='utf-8').read()
    
    def getText(self):
        return self.Text

In [94]:
tekstas = TxtReader('h.txt')
print(tekstas.getText())

Lietuva, Tėvyne mūsų
Tu didvyrių žeme,
Iš praeities Tavo sūnūs
Te stiprybę semia.

Tegul Tavo vaikai eina
Vien takais dorybės
Tegul dirba Tavo naudai
Ir žmonių gėrybei.

Tegul saulė Lietuvoj
Tamsumas prašalina,
Ir šviesa, ir tiesa
Mūs žingsnius telydi.

Tegul meilė Lietuvos
Dega mūsų širdyse,
Vardan tos Lietuvos
Vienybė težydi!


In [105]:
#parašykite klasę TxtAnalyzer, kuriai kreipimosi metu galima būtų
# nurodyti failo pavadinimą ir stulpelių skirtuką.
#klasė sukūrimo metu turi nuskaityti failą, stulpelius skaičių suskirstyti
# į sąrašus ir juos priskirti atributams X, Y ir Z.
#Realizuokite metodus, kurie grąžintų X, Y, Z sąrašų vidurkius, minimalias
# ir maksimalias vertes. Pythone yra min, max, sum funkcijos;

class TxtAnalyzer():
    def __init__(self, failas, skirtukas):
        self.turinys = open(failas, mode='r', encoding='utf-8').readlines()
        self.X = [float(eilute.split(skirtukas)[0]) for eilute in self.turinys]
        self.Y = [float(eilute.split(skirtukas)[1]) for eilute in self.turinys]
        self.Z = [float(eilute.split(skirtukas)[2]) for eilute in self.turinys]
    def list_min(self):
        return min(self.X), min(self.Y), min(self.Z)
    def list_max(self):
        return max(self.X), max(self.Y), max(self.Z)
    def list_avg(self):
        return sum(self.X)/len(self.X), sum(self.Y)/len(self.Y), sum(self.Z)/len(self.Z)

In [107]:
failas = TxtAnalyzer('data1.txt', ';')
a, b, c = failas.list_min()
print(a, b, c, sep='\n')
d, e, f = failas.list_avg()
print(d, e, f, sep='\n')

1.0
0.0062
0.2653
49.7
0.484531
21.949302


In [ ]:
class TxtAnalyzer():
    def __init__(self, pav, skirtukas):
        self.pavadinimas = pav
        self.skirt = skirtukas
        self.x = []
        self.y = []
        self.z = []
        pass
    def TxtReader(self):
        fname = self.pavadinimas
        f = open(fname, mode='r', encoding='utf-8')
        tekstas = f.readlines()
        print(tekstas)
        f.close()
        for x in tekstas:
            self.x.append(float(x.split(self.skirt)[0]))
            self.y.append(float(x.split(self.skirt)[1]))
            self.z.append(float(x.split(self.skirt)[2]))
        print(self.x)
        print(self.y)
        print(self.z)



z = TxtAnalyzer('data/data0.txt',';')
z.TxtReader()

In [108]:
#Sukurkite klasę Rutulys
#kuriai galėtumėte nurodyti Rutulio spindulį r.
#Sukurkite metodus, skirtus rasti jo Tūriui ir paviršiaus plotui;
#Taip pat metodą, kuriuo jūs pakeistumėte spindulio r reikšmę.

class Sphere():
    def __init__(self, r):
        self.radius = r
    
    def GetVolume(self):
        return 4/3*3.14*self.radius**3
    
    def GetSurfaceArea(self):
        return 4*3.14*self.radius**2
    
    def SetRadius(self, new_radius):
        self.radius = new_radius

In [111]:
rutulys = Sphere(15)
print(rutulys.GetVolume(), rutulys.GetSurfaceArea(), sep='\n')
rutulys.SetRadius(20)
print(rutulys.GetVolume(), rutulys.GetSurfaceArea(), sep='\n')

14130.0
2826.0
33493.333333333336
5024.0


In [162]:
#užduotis su paveldjimu:
#parašykite klasę Rectangle, kurioje būtų ilgio ir pločio atributai, bei du metodai - getS - plotui ir getP -erimetrui rasti
#Sukurkite išvestinę (child) klasę Kubas, kuri papildomai turėtų Tūrio skaičiavimo metodą
#• Klasę Piramidė - išvestinė klasė (child class). Pridėkite
# papildomą funkcionalumą - metodą, argumentus piramidės
# tūrio skaičiavimui.

a=()
b=()
c=()


class Rectangle():
    def __init__(self, a, b):
        self.plotas = a*b
        self.perimetras = 2*(a+b)
    
    def CalculatePlotas(self):
        return self.plotas
    
    def CalculatePerimetras(self):
        return self.perimetras

class Kubas(Rectangle):
    def __init__(self, a, b, c):
        super().__init__(a, b)
        self.turis = a*b*c
    def CalculateTuris(self):
        return self.turis

staciakampis = Rectangle(10,20)
gretasienis = Kubas(5,6,7)

print(staciakampis.CalculatePlotas(), gretasienis.CalculateTuris(), sep='\n')

class Pyramid(Kubas):
    def CalculateTuris(self):
        return self.turis/3

piramide = Pyramid(5,6,7)
print(piramide.CalculateTuris())

200
210
70.0


In [ ]:
#Parašykite klasę Apskritimas, kuriai glite nurodyti apskritimo spindulį r.
# Erealizuokite du metodus getS ir getP, plotui ir perimetrui gražinti.

#advanced Apskritimas:
#padarykite taip, jog klasė Apskritimas turėtų atributus S ir P, plotui ir perimetrui, ir kad atnaujinus spindulį r, automatiškai pasikeistų S ir P atributų reikšmės, o getS, getP metodai, kaip ir anksčiau grąžintų S ir P atributų reikšmes.

#advanced Apskritimas:
#padarykite taip, jog klasė Apskritimas turėtų atributus S ir P, plotui ir perimetrui, 
# ir kad atnaujinus spindulį r, automatiškai pasikeistų S ir P atributų reikšmės, o getS, 
# getP metodai, kaip ir anksčiau grąžintų S ir P atributų reikšmes.
class Apskritimas():
    def __init__(self, r):
        self.r = r
        self.S = 2*3.14*r**2
        self.P = 2*3.14*r
        
    def getS(self):
        return self.S
    
    def getP (self):
        return self.P
    
    def change (self, new_r):
        self.r = new_r
        self.S = 2*3.14*new_r**2
        self.P = 2*3.14*new_r
    
aps = Apskritimas(5)
print(aps.getS())
print(aps.getP())
aps.change(10)
print(aps.getS())
print(aps.getP())

In [ ]:
#advanced Apskritimas:
#padarykite taip, jog klasė Apskritimas turėtų atributus S ir P, plotui ir perimetrui, 
# ir kad atnaujinus spindulį r, automatiškai pasikeistų S ir P atributų reikšmės, o getS, 
# getP metodai, kaip ir anksčiau grąžintų S ir P atributų reikšmes.

class Apskritimas():
    def __init__(self, r):
        self.R = r
        self.S = 0
        self.P = 0
        self.upadeAll()
    
    def getP(self):
        return self.P
    
    def getS(self):
        return self.S
    
    def upadeAll(self):
        self.S = 3.14*self.R**2
        self.P = 2*3.14*self.R
        
    def change(self, new_r):
        self.R = new_r
        self.upadeAll()

a = Apskritimas(5)
print(a.getP(), a.getS())
a.change(10)
print(a.getP(), a.getS())

In [7]:
#su paveldėjimu:
# Sukurkite klasę Vehicle su tokiais atributais - Pavadinimas, Rida
#Sukurkite išvestines klases Car, Bus, Train, kurie paveldėtų viską iš Vehicle,
# ir papildomai būtų galima nurodyti Seats - sėdimų vietų skaičių,
# ir visi turėtų metoda GetSeats() grąžinantį tekstą: <Pavadinimas> turi <Seats> sėdimų vietų.

# class Vehicle():
#     def __init__(self, a, b):
#         self.pavadinimas = a
#         self.rida = b

# class Car(Vehicle):
#     def __init__(self, a, b, c):
#         super().__init__(a, b)
#         self.vietos = c
#     def GetSeats(self):
#         return f'{self.pavadinimas} turi {self.vietos} sėdimų vietų'
    
# class Bus(Vehicle):
#     def __init__(self, a, b, c):
#         super().__init__(a, b)
#         self.vietos = c
#     def GetSeats(self):
#         return f'{self.pavadinimas} turi {self.vietos} sėdimų vietų'
    
# class Train(Vehicle):
#     def __init__(self, a, b, c):
#         super().__init__(a, b)
#         self.vietos = c
#     def GetSeats(self):
#         return f'{self.pavadinimas} turi {self.vietos} sėdimų vietų'

vehicle1 = Car('Toyota', 300000, 10)
vehicle2 = Bus('Volvo', 500000, 50)
vehicle3 = Train('LG', 400000, 100)
print(vehicle1.GetSeats(), vehicle2.GetSeats(), vehicle3.GetSeats(), sep='\n')

Toyota turi 10 sėdimų vietų
Volvo turi 50 sėdimų vietų
LG turi 100 sėdimų vietų


In [1]:
x = [1,2,3,4,5]

y = [skaicius-0.75 for skaicius in x]
print(y)

[0.25, 1.25, 2.25, 3.25, 4.25]


In [2]:
import numpy as np

In [4]:
# array
x = np.arange(0, 10, 2)
print(x)

[0 2 4 6 8]


In [5]:
y = x-0.75
print(y)

[-0.75  1.25  3.25  5.25  7.25]


In [6]:
print(np.average(x))
print(np.min(x))
print(np.max(x))
print(np.mean(x))
print(np.median(x))

4.0
0
8
4.0
4.0


In [7]:
a_list = [i for i in range(1,11)]
print(a_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [8]:
a_array = np.asarray(a_list)
print(a_array+0.75)

[ 1.75  2.75  3.75  4.75  5.75  6.75  7.75  8.75  9.75 10.75]


In [9]:
x = [1,2,3]
y = [1,4,5]
x_np = np.asarray(x)
y_np = np.asarray(y)
c = x_np*y_np
print(c)

[ 1  8 15]


In [11]:
print(np.random.randint(0,100))

93


In [15]:
print(np.random.randint(0,100, 10))

[98 78 12 56 48 73 31 72 44 98]


In [13]:
atsitiktinis_float = np.random.rand()
print(atsitiktinis_float)

0.607440619878876


In [14]:
atsitiktinis_float = np.random.rand(100)
print(atsitiktinis_float)

[0.77246994 0.53232951 0.86289287 0.1261895  0.82432188 0.03271434
 0.94616652 0.63766508 0.60466186 0.04121339 0.72314707 0.90894718
 0.96914774 0.58780702 0.39691805 0.26970727 0.32151629 0.22808912
 0.90709333 0.56328293 0.83913116 0.76436422 0.64227273 0.61994407
 0.2773518  0.64756477 0.55539894 0.21122625 0.79135775 0.78143063
 0.84315632 0.72176521 0.35866794 0.64461912 0.41316847 0.26283588
 0.25043961 0.84986932 0.66556985 0.53954869 0.51270769 0.76598708
 0.32551728 0.08763635 0.95194941 0.75030258 0.2758804  0.54534873
 0.27971695 0.5827433  0.64866229 0.92000795 0.57988751 0.41365229
 0.72391474 0.93910905 0.43201628 0.80999487 0.34767633 0.78160631
 0.87128958 0.27782835 0.18597007 0.80019628 0.30942275 0.81066205
 0.8500731  0.15000806 0.43451887 0.86625514 0.15521295 0.71518379
 0.74114102 0.23537851 0.6847742  0.30318183 0.92520949 0.41067679
 0.95284509 0.32521762 0.47948879 0.79336869 0.19653008 0.82225451
 0.28464378 0.02692785 0.86506102 0.80913143 0.41559071 0.9661

In [19]:
xas = np.random.randint(1,10,100)
svoriai = np.random.rand(100)
vidurkis = np.mean(xas)
print(vidurkis)
sv_vid = np.average(xas)
print(sv_vid)
sv_vid2 = np.average(xas, weights=svoriai)
print(sv_vid2)
print(np.median(xas))

5.5
5.5
5.697459209571594
6.0


In [20]:
l = np.linspace(1,10)
print(l)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [21]:
l = np.linspace(1,10,10)
print(l)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [27]:
l = np.linspace(0,10,11)
print(l)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [28]:
l = np.linspace(0,10,15)
print(l)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [29]:
l = np.linspace(0,10,15, endpoint=False)
print(l)

[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.         6.66666667 7.33333333
 8.         8.66666667 9.33333333]


In [33]:
n_np = np.arange(0,10)
# kaip metodai
print(n_np.max())
print(max(n_np))
print(n_np.mean())
print(n_np.min())

9
9
4.5
0


In [ ]:
# kam šita?
%load_ext autoreload

In [ ]:
# kam šita?
%autoreload 2

In [2]:
import modulis

In [3]:
vehicle1 = modulis.Car('Toyota', 300000, 10)
vehicle2 = modulis.Bus('Volvo', 500000, 50)
vehicle3 = modulis.Train('LG', 400000, 100)
print(vehicle1.GetSeats(), vehicle2.GetSeats(), vehicle3.GetSeats(), sep='\n')

Toyota turi 10 sėdimų vietų
Volvo turi 50 sėdimų vietų
LG turi 100 sėdimų vietų


In [39]:
#sukurkite failus nuskaitančią klasę, ji turi būti aprašyta jūsų kuriamame modulyje;
#ta klasė turi nuskaityti pateiktą failą, ir suskaidyti stulpelius į sąrašus:
#sąrašai I, U, j, P, duomenys iš juos iš atitinkamų taip pat pavadintų stulpelių
#realizuokite tai, jog klasė rastų tokį dydį - maksimalų P, suskaičiuotų tokį dydį pce = Pmax / 1000 * 100%;
#šie dydžiai turi būti pasiekiamį arba kaip atributas, arba galite įdėti metodą jam gauti

# class ReadFilesJono():
#     def __init__(self, file):
#         file_content = open(file, mode='r', encoding='utf-8').readlines()
#         self.U = [float(eilute.split(';')[0]) for eilute in file_content[1:]]
#         self.I = []
#         for eilute in file_content[1:]:
#             try:
#                 self.I.append(float(eilute.split(';')[1]))
#             except:
#                 self.I.append(float(0))
#         self.j = [float(eilute.split(';')[2]) for eilute in file_content[1:]]
#         self.P = [float(eilute.split(';')[3].strip()) for eilute in file_content[1:]]
#         self.max_P = max(self.P)
#         self.pce = f'{self.max_P/1000*100}%' 
#         self.U_when_j_zero = [U for U, j in zip(self.U, self.j) if round(j, 0) == 0]
#         self.j_when_U_zero = [j for U, j in zip(self.U, self.j) if round(U, 0) == 0]
#         print(self.U_when_j_zero)


In [1]:
import os
print(os.getcwd())
os.chdir('../../')
print(os.getcwd())
import ReadFilesJono as rfj
file_name = 'REF_D_2k_FW_2.03.dat'
file = rfj.ReadFilesJono(file_name)
print(file.j)
print(file.max_P)
print(file.pce)
print(file.U_when_j_zero)
print(file.j_when_U_zero)

c:\Users\User\OneDrive\Stalinis kompiuteris\Python mokymai\GIT_Repository\python_mokymai
c:\Users\User\OneDrive\Stalinis kompiuteris\Python mokymai
[14.9012, 11.0532262, 8.5054112, 6.25028, 4.2308987, 2.4865837, 0.9452886, -0.3914982, -1.4925188, -2.4702462, -3.22762, -3.8494512, -4.3999025, -4.8577025, -5.2581838, -5.640395, -5.9576813, -6.2209775, -6.4703212, -6.707795, -6.8878487, -7.095295, -7.2327912, -7.4043387, -7.535765, -7.6644625, -7.7971937, -7.9071088, -8.0151288, -8.1142225, -8.1840213, -8.2883813, -8.3483275, -8.4491925, -8.536865, -8.61116, -8.6619513, -8.7167575, -8.7752387, -8.847965, -8.9324613, -8.9389112, -9.0025137, -9.0146713, -9.1136525, -9.1544038, -9.2018787, -9.2303375, -9.251265, -9.2749937, -9.3266075, -9.3552425, -9.4106112, -9.4215063, -9.4691725, -9.4935375, -9.5230788, -9.5530775, -9.5864112, -9.6139637, -9.5779563]
17.88144
1.7881440000000002%
[1.0366667]
[-8.1840213, -8.2883813, -8.3483275, -8.4491925, -8.536865, -8.61116, -8.6619513, -8.7167575, -8.77